### ISSUE TITLE
Fails on MacOS

### ISSUE THREAD

**Issue by adocherty** [conda-forge/watchdog-feedstock#4]
There is a known issue with this version of watchdog which causes watchmedo to fail on MacOS with the error:

> FileNotFoundError: [Errno 2] No such file or directory: 'setsid'

There is a patch from 2015 that fixes this, but is not included in the current conda-forge (or pypi) version:
https://github.com/gorakhargosh/watchdog/pull/329

**Comment by dan-kez** [comment]
I'm having the same issue, It would be really helpful to cut a new version with this fix.
